"""Initial schema: projects, files, ficha-base, circuits and the insert-only audit log.

Revision ID: 0001
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("actor_type", sa.String(length=10), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "actor_type IN ('agent', 'user', 'system')", name="ck_audit_event_actor_type"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("building_type", sa.String(length=120), nullable=True),
        sa.Column("phase", sa.String(length=20), nullable=False),
        sa.Column("specialties", postgresql.ARRAY(sa.String(length=20)), nullable=False),
        sa.Column("public_procurement", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.CheckConstraint("phase IN ('licenciamento', 'execucao')", name="ck_project_phase"),
        sa.CheckConstraint("status IN ('active', 'archived')", name="ck_project_status"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "ficha_revision",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("confirmed_by", sa.String(length=64), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'confirmed', 'superseded')", name="ck_ficha_revision_status"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "label", name="uq_ficha_revision_label"),
    )
    op.create_table(
        "project_file",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("version_label", sa.String(length=20), nullable=True),
        sa.Column("file_date", sa.Date(), nullable=True),
        sa.Column("template_version", sa.String(length=40), nullable=True),
        sa.Column("ingest_status", sa.String(length=20), nullable=False),
        sa.Column("ingest_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "ingest_status IN ('pending', 'running', 'done', 'failed', 'skipped')",
            name="ck_project_file_ingest_status",
        ),
        sa.CheckConstraint(
            "kind IN ('ficha_eletrotecnica', 'calc_summary', 'calc_circuit', 'mqt', 'lpu', 'drawing_pdf', 'drawing_dwg', 'archive_docx', 'other')",
            name="ck_project_file_kind",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "checksum", name="uq_project_file_checksum"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_table(
        "circuit",
        sa.Column("revision_id", sa.UUID(), nullable=False),
        sa.Column("source_file_id", sa.UUID(), nullable=True),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=80), nullable=True),
        sa.Column("origin", sa.String(length=80), nullable=True),
        sa.Column("destination", sa.String(length=80), nullable=True),
        sa.Column("kva", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("voltage_v", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("protection_type", sa.String(length=2), nullable=True),
        sa.Column("ib_a", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("in_a", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("idn_ma", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("iz_a", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("i2_a", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("iz145_a", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("cable_raw", sa.String(length=120), nullable=True),
        sa.Column("cable_normalized", sa.String(length=120), nullable=True),
        sa.Column("length_m", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("vd_section_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("vd_upstream_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("vd_total_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("breaking_capacity_ka", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("pole_type", sa.String(length=3), nullable=True),
        sa.Column("installation", sa.String(length=3), nullable=True),
        sa.Column("phases", sa.Integer(), nullable=True),
        sa.Column("insulation", sa.String(length=40), nullable=True),
        sa.Column("conductor", sa.String(length=2), nullable=True),
        sa.Column("ref_method", sa.String(length=20), nullable=True),
        sa.Column("rtiebt_table", sa.String(length=40), nullable=True),
        sa.Column("source_ref", sa.String(length=160), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "conductor IS NULL OR conductor IN ('Cu', 'Al')", name="ck_circuit_conductor"
        ),
        sa.CheckConstraint(
            "installation IS NULL OR installation IN ('TUB', 'EST', 'ENT', 'AR')",
            name="ck_circuit_installation",
        ),
        sa.CheckConstraint(
            "pole_type IS NULL OR pole_type IN ('MON', 'MUL')", name="ck_circuit_pole_type"
        ),
        sa.CheckConstraint(
            "protection_type IS NULL OR protection_type IN ('D', 'F')",
            name="ck_circuit_protection_type",
        ),
        sa.ForeignKeyConstraint(["revision_id"], ["ficha_revision.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_file_id"], ["project_file.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ficha_value",
        sa.Column("revision_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("group", sa.String(length=40), nullable=False),
        sa.Column("label_pt", sa.String(length=160), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("personal_data", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_ref", sa.String(length=160), nullable=True),
        sa.Column("source_file_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "source_type IN ('ficha_eletrotecnica', 'calc', 'mqt', 'drawing', 'manual')",
            name="ck_ficha_value_source_type",
        ),
        sa.CheckConstraint(
            "status IN ('confirmed', 'conflict', 'pending')", name="ck_ficha_value_status"
        ),
        sa.ForeignKeyConstraint(["revision_id"], ["ficha_revision.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_file_id"], ["project_file.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("revision_id", "key", name="uq_ficha_value_key"),
    )
    op.create_table(
        "ficha_conflict",
        sa.Column("value_id", sa.UUID(), nullable=False),
        sa.Column("candidates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resolved_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("resolved_by", sa.String(length=64), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["value_id"], ["ficha_value.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    op.create_index("ix_audit_event_entity", "audit_event", ["entity_type", "entity_id"])
    op.create_index("ix_audit_event_at", "audit_event", ["at"])
    op.create_index("ix_circuit_revision_id", "circuit", ["revision_id", "row_index"])
    op.create_index("ix_ficha_conflict_value_id", "ficha_conflict", ["value_id"])
    # SPEC P7: the audit log is insert-only, enforced by the database itself.
    op.execute(AUDIT_IMMUTABLE_FUNCTION)
    op.execute(
        "CREATE TRIGGER audit_event_no_update_delete BEFORE UPDATE OR DELETE ON audit_event "
        "FOR EACH ROW EXECUTE FUNCTION audit_event_immutable()"
    )
    op.execute(
        "CREATE TRIGGER audit_event_no_truncate BEFORE TRUNCATE ON audit_event "
        "FOR EACH STATEMENT EXECUTE FUNCTION audit_event_immutable()"
    )


AUDIT_IMMUTABLE_FUNCTION = """
CREATE FUNCTION audit_event_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_event is insert-only' USING ERRCODE = 'insufficient_privilege';
END
$$
"""


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_event_no_truncate ON audit_event")
    op.execute("DROP TRIGGER IF EXISTS audit_event_no_update_delete ON audit_event")
    op.execute("DROP FUNCTION IF EXISTS audit_event_immutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ficha_conflict")
    op.drop_table("ficha_value")
    op.drop_table("circuit")
    op.drop_table("project_file")
    op.drop_table("ficha_revision")
    op.drop_table("project")
    op.drop_table("audit_event")
    # ### end Alembic commands ###
