"""Phase 4: documents, sections, their versions, citations and value references.

Revision ID: 0010
Revises: 0009
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=15), nullable=False),
        sa.Column("specialty", sa.String(length=20), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=True),
        sa.Column("ficha_revision_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=15), nullable=False),
        sa.Column("responsible_user_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'in_review', 'approved')", name="ck_document_status"
        ),
        sa.CheckConstraint(
            "type IN ('MDJ', 'CTE', 'FICHA_ELE', 'IDENTIFICACAO', 'TERMO')", name="ck_document_type"
        ),
        sa.ForeignKeyConstraint(["ficha_revision_id"], ["ficha_revision.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["template_id"], ["source_document.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "section",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("block_id", sa.UUID(), nullable=True),
        sa.Column("block_key", sa.String(length=200), nullable=False),
        sa.Column("block_version", sa.Integer(), nullable=False),
        sa.Column("block_status", sa.String(length=10), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("active_reason", sa.Text(), nullable=True),
        sa.Column("activation_override", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("status_note", sa.Text(), nullable=True),
        sa.Column("missing_keys", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("unlocked", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("equipment_slots", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("reviewed_by", sa.String(length=64), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "kind IN ('cover', 'index', 'block', 'signature')", name="ck_section_kind"
        ),
        sa.CheckConstraint("mode IN ('fixed', 'parametric', 'adaptive')", name="ck_section_mode"),
        sa.CheckConstraint(
            "status IN ('todo', 'generated', 'reviewed', 'alert')", name="ck_section_status"
        ),
        sa.ForeignKeyConstraint(["block_id"], ["template_block.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "order", name="uq_section_order"),
    )
    op.create_table(
        "section_version",
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("author_type", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("llm_call_id", sa.UUID(), nullable=True),
        sa.Column("request", sa.Text(), nullable=True),
        sa.Column("missing_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("issues", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "author_type IN ('agent', 'user', 'system')", name="ck_section_version_author_type"
        ),
        sa.CheckConstraint(
            "status IN ('current', 'proposed', 'rejected', 'superseded')",
            name="ck_section_version_status",
        ),
        sa.ForeignKeyConstraint(["section_id"], ["section.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("section_id", "number", name="uq_section_version_number"),
    )
    op.create_table(
        "citation",
        sa.Column("section_version_id", sa.UUID(), nullable=False),
        sa.Column("anchor", sa.String(length=40), nullable=False),
        sa.Column("kind", sa.String(length=15), nullable=False),
        sa.Column("target_id", sa.String(length=200), nullable=False),
        sa.Column("locator", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["section_version_id"], ["section_version.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "value_ref",
        sa.Column("section_version_id", sa.UUID(), nullable=False),
        sa.Column("anchor", sa.String(length=40), nullable=False),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("ficha_value_id", sa.UUID(), nullable=True),
        sa.Column("circuit_id", sa.UUID(), nullable=True),
        sa.Column("bom_item_id", sa.UUID(), nullable=True),
        sa.Column("field", sa.String(length=40), nullable=True),
        sa.Column("rendered_text", sa.Text(), nullable=True),
        sa.Column("personal", sa.Boolean(), nullable=False),
        sa.Column("edited", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["bom_item_id"], ["bom_item.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["circuit_id"], ["circuit.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["ficha_value_id"], ["ficha_value.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["section_version_id"], ["section_version.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "project", sa.Column("llm_allowed", sa.Boolean(), server_default="false", nullable=False)
    )
    op.create_index("ix_document_project_id", "document", ["project_id"])
    op.create_index("ix_section_document_id", "section", ["document_id"])
    op.create_index("ix_section_version_section_id", "section_version", ["section_id"])
    op.create_index("ix_citation_section_version_id", "citation", ["section_version_id"])
    op.create_index("ix_value_ref_section_version_id", "value_ref", ["section_version_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "llm_allowed")
    op.drop_table("value_ref")
    op.drop_table("citation")
    op.drop_table("section_version")
    op.drop_table("section")
    op.drop_table("document")
    # ### end Alembic commands ###
